#!/bin/bash

if [ $# != 4 ] ; #Nos aseguramos de que el numero de parámetros es el correcto
then
	echo "Número de parámetros erróneo"
	echo "Uso: ./crearGráfica <ficheroDatos> <carpetaGuardado> <paramX> <paramY> "
else

gnuplot <<- BEGIN_GNUPLOT
	set term png
	set output "$2/grafica.png"
	set title "$1"
	set xlabel "$3"
	set ylabel "$4"
	set grid
	f(x)=a*x**( log(3)/log(2) ) 
	fit f(x) "$1" via a
	plot f(x) , "$1"
	BEGIN_GNUPLOT

fi
